"""Маппинг названий стран EN → RU + флаги."""

from __future__ import annotations

_EN_TO_RU: dict[str, str] = {
    "world": "Международные",
    "international": "Международные",
    "europe": "Европа",
    "uefa": "УЕФА",
    "south-america": "Южная Америка",
    "north-central-america": "Северная и Центральная Америка",
    "asia": "Азия",
    "africa": "Африка",
    "oceania": "Океания",
    "albania": "Албания",
    "algeria": "Алжир",
    "andorra": "Андорра",
    "angola": "Ангола",
    "argentina": "Аргентина",
    "armenia": "Армения",
    "australia": "Австралия",
    "austria": "Австрия",
    "azerbaijan": "Азербайджан",
    "bahrain": "Бахрейн",
    "bangladesh": "Бангладеш",
    "belarus": "Беларусь",
    "belgium": "Бельгия",
    "bolivia": "Боливия",
    "bosnia": "Босния и Герцеговина",
    "bosnia-and-herzegovina": "Босния и Герцеговина",
    "botswana": "Ботсвана",
    "brazil": "Бразилия",
    "bulgaria": "Болгария",
    "burkina-faso": "Буркина-Фасо",
    "burundi": "Бурунди",
    "cambodia": "Камбоджа",
    "cameroon": "Камерун",
    "canada": "Канада",
    "chile": "Чили",
    "china": "Китай",
    "china-pr": "Китай",
    "colombia": "Колумбия",
    "congo": "Конго",
    "costa-rica": "Коста-Рика",
    "ivory-coast": "Кот-д’Ивуар",
    "croatia": "Хорватия",
    "cuba": "Куба",
    "cyprus": "Кипр",
    "czech-republic": "Чехия",
    "czechia": "Чехия",
    "denmark": "Дания",
    "ecuador": "Эквадор",
    "egypt": "Египет",
    "el-salvador": "Сальвадор",
    "england": "Англия",
    "estonia": "Эстония",
    "ethiopia": "Эфиопия",
    "faroe-islands": "Фарерские острова",
    "finland": "Финляндия",
    "france": "Франция",
    "gabon": "Габон",
    "gambia": "Гамбия",
    "georgia": "Грузия",
    "germany": "Германия",
    "ghana": "Гана",
    "greece": "Греция",
    "guatemala": "Гватемала",
    "honduras": "Гондурас",
    "hong-kong": "Гонконг",
    "hungary": "Венгрия",
    "iceland": "Исландия",
    "india": "Индия",
    "indonesia": "Индонезия",
    "iran": "Иран",
    "iraq": "Ирак",
    "ireland": "Ирландия",
    "israel": "Израиль",
    "italy": "Италия",
    "jamaica": "Ямайка",
    "japan": "Япония",
    "jordan": "Иордания",
    "kazakhstan": "Казахстан",
    "kenya": "Кения",
    "kosovo": "Косово",
    "kuwait": "Кувейт",
    "kyrgyzstan": "Киргизия",
    "latvia": "Латвия",
    "lebanon": "Ливан",
    "libya": "Ливия",
    "liechtenstein": "Лихтенштейн",
    "lithuania": "Литва",
    "luxembourg": "Люксембург",
    "malaysia": "Малайзия",
    "malta": "Мальта",
    "mexico": "Мексика",
    "moldova": "Молдова",
    "monaco": "Монако",
    "mongolia": "Монголия",
    "montenegro": "Черногория",
    "morocco": "Марокко",
    "myanmar": "Мьянма",
    "namibia": "Намибия",
    "nepal": "Непал",
    "netherlands": "Нидерланды",
    "new-zealand": "Новая Зеландия",
    "nicaragua": "Никарагуа",
    "nigeria": "Нигерия",
    "north-korea": "Северная Корея",
    "north-macedonia": "Северная Македония",
    "macedonia": "Северная Македония",
    "northern-ireland": "Северная Ирландия",
    "norway": "Норвегия",
    "oman": "Оман",
    "pakistan": "Пакистан",
    "palestine": "Палестина",
    "panama": "Панама",
    "paraguay": "Парагвай",
    "peru": "Перу",
    "philippines": "Филиппины",
    "poland": "Польша",
    "portugal": "Португалия",
    "qatar": "Катар",
    "romania": "Румыния",
    "russia": "Россия",
    "rwanda": "Руанда",
    "san-marino": "Сан-Марино",
    "saudi-arabia": "Саудовская Аравия",
    "scotland": "Шотландия",
    "senegal": "Сенегал",
    "serbia": "Сербия",
    "singapore": "Сингапур",
    "slovakia": "Словакия",
    "slovenia": "Словения",
    "south-africa": "ЮАР",
    "south-korea": "Южная Корея",
    "korea-republic": "Южная Корея",
    "spain": "Испания",
    "sri-lanka": "Шри-Ланка",
    "sweden": "Швеция",
    "switzerland": "Швейцария",
    "syria": "Сирия",
    "taiwan": "Тайвань",
    "tajikistan": "Таджикистан",
    "tanzania": "Танзания",
    "thailand": "Таиланд",
    "trinidad-and-tobago": "Тринидад и Тобаго",
    "tunisia": "Тунис",
    "turkey": "Турция",
    "turkmenistan": "Туркменистан",
    "uganda": "Уганда",
    "ukraine": "Украина",
    "united-arab-emirates": "ОАЭ",
    "uae": "ОАЭ",
    "united-states": "США",
    "usa": "США",
    "uruguay": "Уругвай",
    "uzbekistan": "Узбекистан",
    "venezuela": "Венесуэла",
    "vietnam": "Вьетнам",
    "wales": "Уэльс",
    "yemen": "Йемен",
    "zambia": "Замбия",
    "zimbabwe": "Зимбабве",
}

_FLAGS: dict[str, str] = {
    "world": "🌍", "international": "🌍", "europe": "🇪🇺", "uefa": "🇪🇺",
    "south-america": "🌎", "north-central-america": "🌎", "asia": "🌏",
    "africa": "🌍", "oceania": "🌏",
    "england": "🏴", "scotland": "🏴", "wales": "🏴", "northern-ireland": "🇮🇪",
    "albania": "🇦🇱", "algeria": "🇩🇿", "andorra": "🇦🇩", "angola": "🇦🇴",
    "argentina": "🇦🇷", "armenia": "🇦🇲", "australia": "🇦🇺", "austria": "🇦🇹",
    "azerbaijan": "🇦🇿", "bahrain": "🇧🇭", "bangladesh": "🇧🇩", "belarus": "🇧🇾",
    "belgium": "🇧🇪", "bolivia": "🇧🇴", "bosnia": "🇧🇦", "bosnia-and-herzegovina": "🇧🇦",
    "botswana": "🇧🇼", "brazil": "🇧🇷", "bulgaria": "🇧🇬", "burkina-faso": "🇧🇫",
    "burundi": "🇧🇮", "cambodia": "🇰🇭", "cameroon": "🇨🇲", "canada": "🇨🇦",
    "chile": "🇨🇱", "china": "🇨🇳", "china-pr": "🇨🇳", "colombia": "🇨🇴",
    "congo": "🇨🇬", "costa-rica": "🇨🇷", "ivory-coast": "🇨🇮", "croatia": "🇭🇷",
    "cuba": "🇨🇺", "cyprus": "🇨🇾", "czech-republic": "🇨🇿", "czechia": "🇨🇿",
    "denmark": "🇩🇰", "ecuador": "🇪🇨", "egypt": "🇪🇬", "el-salvador": "🇸🇻",
    "estonia": "🇪🇪", "ethiopia": "🇪🇹", "faroe-islands": "🇫🇴", "finland": "🇫🇮",
    "france": "🇫🇷", "gabon": "🇬🇦", "gambia": "🇬🇲", "georgia": "🇬🇪",
    "germany": "🇩🇪", "ghana": "🇬🇭", "greece": "🇬🇷", "guatemala": "🇬🇹",
    "honduras": "🇭🇳", "hong-kong": "🇭🇰", "hungary": "🇭🇺", "iceland": "🇮🇸",
    "india": "🇮🇳", "indonesia": "🇮🇩", "iran": "🇮🇷", "iraq": "🇮🇶",
    "ireland": "🇮🇪", "israel": "🇮🇱", "italy": "🇮🇹", "jamaica": "🇯🇲",
    "japan": "🇯🇵", "jordan": "🇯🇴", "kazakhstan": "🇰🇿", "kenya": "🇰🇪",
    "kosovo": "🇽🇰", "kuwait": "🇰🇼", "kyrgyzstan": "🇰🇬", "latvia": "🇱🇻",
    "lebanon": "🇱🇧", "libya": "🇱🇾", "liechtenstein": "🇱🇮", "lithuania": "🇱🇹",
    "luxembourg": "🇱🇺", "malaysia": "🇲🇾", "malta": "🇲🇹", "mexico": "🇲🇽",
    "moldova": "🇲🇩", "monaco": "🇲🇨", "mongolia": "🇲🇳", "montenegro": "🇲🇪",
    "morocco": "🇲🇦", "myanmar": "🇲🇲", "namibia": "🇳🇦", "nepal": "🇳🇵",
    "netherlands": "🇳🇱", "new-zealand": "🇳🇿", "nicaragua": "🇳🇮", "nigeria": "🇳🇬",
    "north-korea": "🇰🇵", "north-macedonia": "🇲🇰", "macedonia": "🇲🇰",
    "norway": "🇳🇴", "oman": "🇴🇲", "pakistan": "🇵🇰", "palestine": "🇵🇸",
    "panama": "🇵🇦", "paraguay": "🇵🇾", "peru": "🇵🇪", "philippines": "🇵🇭",
    "poland": "🇵🇱", "portugal": "🇵🇹", "qatar": "🇶🇦", "romania": "🇷🇴",
    "russia": "🇷🇺", "rwanda": "🇷🇼", "san-marino": "🇸🇲", "saudi-arabia": "🇸🇦",
    "senegal": "🇸🇳", "serbia": "🇷🇸", "singapore": "🇸🇬", "slovakia": "🇸🇰",
    "slovenia": "🇸🇮", "south-africa": "🇿🇦", "south-korea": "🇰🇷",
    "korea-republic": "🇰🇷", "spain": "🇪🇸", "sri-lanka": "🇱🇰", "sweden": "🇸🇪",
    "switzerland": "🇨🇭", "syria": "🇸🇾", "taiwan": "🇹🇼", "tajikistan": "🇹🇯",
    "tanzania": "🇹🇿", "thailand": "🇹🇭", "trinidad-and-tobago": "🇹🇹",
    "tunisia": "🇹🇳", "turkey": "🇹🇷", "turkmenistan": "🇹🇲", "uganda": "🇺🇬",
    "ukraine": "🇺🇦", "united-arab-emirates": "🇦🇪", "uae": "🇦🇪",
    "united-states": "🇺🇸", "usa": "🇺🇸", "uruguay": "🇺🇾", "uzbekistan": "🇺🇿",
    "venezuela": "🇻🇪", "vietnam": "🇻🇳", "yemen": "🇾🇪", "zambia": "🇿🇲",
    "zimbabwe": "🇿🇼",
}


def _normalize(name: str | None) -> str:
    if not name:
        return ""
    return name.strip().lower().replace("_", "-").replace(" ", "-")


def country_ru(name: str | None) -> str:
    if not name:
        return ""
    return _EN_TO_RU.get(_normalize(name), name)


def country_flag(name: str | None) -> str:
    if not name:
        return "🌐"
    return _FLAGS.get(_normalize(name), "🌐")


def format_country(name: str | None, *, with_flag: bool = True) -> str:
    if not name:
        return "🌐 Неизвестно"
    ru = country_ru(name)
    if not with_flag:
        return ru
    return f"{country_flag(name)} {ru}"


__all__ = ["country_flag", "country_ru", "format_country"]
